#!/user/bin/env/python

import subprocess

subprocess.call("ifconfig",shell=True)
subprocess.call("ifconfig eth0 down",shell=True)
subprocess.call("ifconfig eth0 hw ether 90:16:ae:80:6d:c9",shell=True)
subprocess.call("ifconfig eth0 up",shell=True)
subprocess.call("ifconfig",shell=True)
